name: Run Docker Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Pull the Docker image from Docker Hub
      - name: Pull and run Docker image
        run: |
          # Pulling the Docker image (you can replace this with your own image)
          docker pull hello-world
          
          # Running the Docker image (this will print Hello World)
          docker run hello-world
