name: Run DockerOperator Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_docker_operator:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub (optional, if the image is private)
      # Uncomment if you are pulling from a private repository on Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Pull and run the Docker image
      - name: Run docker image with Python script
        run: |
          docker pull deet1107/gesture_model_airflow
          docker run deet1107/gesture_model_airflow python main.py
