name: v_test_docker_harbor

on:
  push:
    branches: [ master ]
jobs:
  v_deploy:
    name: v_deployjob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: print python hello
        run: |
          python3 hello.py
      - name: Login to Dockerharbor
        uses: docker/login-action@v1
        with:
          registry: demo.goharbor.io
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: build and release to harbor
        run: |
          docker build -t demo.goharbor.io/test-tedkim/test-image:v0.2 . 
          docker push demo.goharbor.io/test-tedkim/test-image:v0.2
      - name: docker pull test from harbor
        run: |
          docker pull demo.goharbor.io/test-tedkim/test-image@sha256:eafe3118c6e5da21f020440f72cca2514a8997ff9c72a8b467e215fdf26f28fc
