name: v_test_docker_harbor

on: push

jobs:
  v_deploy:
    name: v_deployjob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Test
        run: |
          print("hello world")
      - name: Login to Dockerharbor
        uses: docker/login-action@v1
        with:
          registry: demo.goharbor.io
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: build and release to DockerHarbor
        run: |
          docker tag SOURCE_IMAGE:TAG demo.goharbor.io/test-tedkim/hello:1.0
          docker push demo.goharbor.io/test-tedkim/hello:1.0
